//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoyashiroKohaku.PngChunkUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoyashiroKohaku.PngChunkUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Chunk type should be 4 byte. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chunk_Constructor_ChunkTypeOutOfRange {
            get {
                return ResourceManager.GetString("Chunk_Constructor_ChunkTypeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk is broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chunk_Constructor_Invalid {
            get {
                return ResourceManager.GetString("Chunk_Constructor_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk is broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkReader_SplitChunk_InvalidChunk {
            get {
                return ResourceManager.GetString("ChunkReader_SplitChunk_InvalidChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image is broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkReader_SplitChunk_InvalidImage {
            get {
                return ResourceManager.GetString("ChunkReader_SplitChunk_InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkWriter_WriteImageBytes_ChunkIsNull {
            get {
                return ResourceManager.GetString("ChunkWriter_WriteImageBytes_ChunkIsNull", resourceCulture);
            }
        }
    }
}
